"""
Training dataset for email classifier with labeled examples.
"""
from typing import List, Tuple


def get_training_data() -> List[Tuple[str, str]]:
    """
    Get training data for the email classifier.
    
    Returns:
        List of tuples (text, category) with 100+ labeled examples
    """
    training_data = [
        # Work emails (25+ examples)
        ("Meeting scheduled for tomorrow at 3pm in conference room B", "Work"),
        ("Project deadline extended to next Friday", "Work"),
        ("Please review the attached quarterly report", "Work"),
        ("Team standup moved to 10am", "Work"),
        ("Your expense report has been approved", "Work"),
        ("Client presentation scheduled for Monday morning", "Work"),
        ("Code review requested for pull request #234", "Work"),
        ("Sprint planning meeting this Thursday", "Work"),
        ("Performance review scheduled next week", "Work"),
        ("Budget approval needed for Q4 initiatives", "Work"),
        ("New employee onboarding session tomorrow", "Work"),
        ("IT security training mandatory for all staff", "Work"),
        ("Office will be closed for maintenance this weekend", "Work"),
        ("Quarterly goals need to be submitted by Friday", "Work"),
        ("Conference call with stakeholders at 2pm", "Work"),
        ("Project status update required", "Work"),
        ("Team building event next month", "Work"),
        ("Annual performance bonus announced", "Work"),
        ("New company policy regarding remote work", "Work"),
        ("Department meeting rescheduled", "Work"),
        ("Action items from yesterday's meeting", "Work"),
        ("Urgent: Server maintenance tonight", "Work"),
        ("Weekly report due by end of day", "Work"),
        ("Training session on new software tools", "Work"),
        ("Vacation request approved", "Work"),
        ("Invoice submitted for payment processing", "Work"),
        ("Contract renewal discussion needed", "Work"),
        ("Collaboration opportunity with partner team", "Work"),
        
        # Personal emails (25+ examples)
        ("Hey, want to grab dinner this weekend?", "Personal"),
        ("Happy birthday! Hope you have a great day", "Personal"),
        ("Thanks for helping me move last Saturday", "Personal"),
        ("Family reunion planned for next month", "Personal"),
        ("Your Amazon order has been delivered", "Personal"),
        ("Reminder: dentist appointment tomorrow at 10am", "Personal"),
        ("Photos from our vacation are ready", "Personal"),
        ("Book club meeting this Thursday evening", "Personal"),
        ("Gym membership renewal notice", "Personal"),
        ("Your prescription is ready for pickup", "Personal"),
        ("Congratulations on your new home!", "Personal"),
        ("Movie night at my place Friday?", "Personal"),
        ("Your flight confirmation for next week", "Personal"),
        ("Package delivery scheduled for tomorrow", "Personal"),
        ("Invitation to wedding ceremony", "Personal"),
        ("Your car service appointment confirmed", "Personal"),
        ("Library books due next week", "Personal"),
        ("Utility bill payment received", "Personal"),
        ("Your subscription has been renewed", "Personal"),
        ("Pet grooming appointment reminder", "Personal"),
        ("Concert tickets purchased successfully", "Personal"),
        ("Your reservation at the restaurant is confirmed", "Personal"),
        ("Bank statement for last month", "Personal"),
        ("Credit card payment processed", "Personal"),
        ("Insurance policy renewal notice", "Personal"),
        ("Your package has shipped and is on the way", "Personal"),
        ("Appointment confirmed with your doctor", "Personal"),
        ("Your order is ready for pickup at the store", "Personal"),
        
        # Spam emails (25+ examples)
        ("Congratulations! You've won $1,000,000 in our lottery", "Spam"),
        ("Click here to claim your free iPhone now!", "Spam"),
        ("Urgent: Your account will be suspended unless you verify", "Spam"),
        ("Make money fast working from home", "Spam"),
        ("You have inherited millions from a distant relative", "Spam"),
        ("Lose 30 pounds in 30 days guaranteed", "Spam"),
        ("Hot singles in your area want to meet you", "Spam"),
        ("Your computer has been infected! Download our antivirus", "Spam"),
        ("Congratulations! You're our lucky winner today", "Spam"),
        ("Get rich quick with this one simple trick", "Spam"),
        ("Claim your prize now before it expires", "Spam"),
        ("You've been selected for a special offer", "Spam"),
        ("Increase your credit score overnight", "Spam"),
        ("Free vacation package - act now!", "Spam"),
        ("Your package is waiting at customs - pay fee to release", "Spam"),
        ("Miracle cure for all diseases discovered", "Spam"),
        ("Work from home and earn thousands per week", "Spam"),
        ("Your email has won our daily prize draw", "Spam"),
        ("Enlarge your muscles with this supplement", "Spam"),
        ("Get a loan approved in minutes no credit check", "Spam"),
        ("You qualify for a government grant", "Spam"),
        ("Click to verify your bank account immediately", "Spam"),
        ("Congratulations you have been chosen", "Spam"),
        ("Limited time offer expires in 1 hour", "Spam"),
        ("Your social security number has been compromised", "Spam"),
        ("IRS tax refund waiting for you", "Spam"),
        ("Nigerian prince needs your help transferring funds", "Spam"),
        ("Free trial no credit card required act now", "Spam"),
        
        # Promotions emails (25+ examples)
        ("50% off sale this weekend only", "Promotions"),
        ("New arrivals in store - shop now", "Promotions"),
        ("Exclusive member discount inside", "Promotions"),
        ("Flash sale: 24 hours only", "Promotions"),
        ("Your coupon code for 20% off", "Promotions"),
        ("Black Friday deals start now", "Promotions"),
        ("Free shipping on orders over $50", "Promotions"),
        ("Clearance sale - up to 70% off", "Promotions"),
        ("New season collection just launched", "Promotions"),
        ("Buy one get one free this week", "Promotions"),
        ("Special offer for loyal customers", "Promotions"),
        ("Limited stock - order now", "Promotions"),
        ("Early access to our summer sale", "Promotions"),
        ("Refer a friend and get $10 credit", "Promotions"),
        ("Weekly deals newsletter", "Promotions"),
        ("Your wishlist items are on sale", "Promotions"),
        ("Cyber Monday exclusive offers", "Promotions"),
        ("End of season clearance event", "Promotions"),
        ("New product launch special pricing", "Promotions"),
        ("VIP early access to sale", "Promotions"),
        ("Double points on all purchases this week", "Promotions"),
        ("Gift with purchase promotion", "Promotions"),
        ("Student discount available", "Promotions"),
        ("Birthday month special offer", "Promotions"),
        ("Loyalty rewards program update", "Promotions"),
        ("Subscribe and save 15%", "Promotions"),
        ("Last chance to save before prices go up", "Promotions"),
        ("Bundle deal - save when you buy more", "Promotions"),
        ("Seasonal sale starts today", "Promotions"),
        ("Exclusive online only offers", "Promotions"),
    ]
    
    return training_data
